<div class="content">
    <form class="form subscribe" novalidate="novalidate" action="http://localhost/newsletter/subscriber/new/" method="post" id="newsletter-validate-detail">
        <div class="field newsletter">
            <div class="control">
                <label for="newsletter">
                    <input name="email" type="email" id="newsletter" placeholder="Email Address" data-validate="{required:true, 'validate-email':true}">
                </label>
            </div>
        </div>
        <div class="actions">
            <button class="action subscribe primary" title="Subscribe" type="submit" aria-label="Subscribe">
                <span>Subscribe</span>
            </button>
        </div>
    </form>
</div>